<?php
/**
 * FreeDNS Panel - Installation Wizard
 * Creates database, admin user, and initial configuration.
 */
error_reporting(E_ALL);
ini_set('display_errors', '0');

$lockFile = __DIR__ . '/.installed';
$step = (int)($_GET['step'] ?? 1);
$errors = [];
$success = '';

if (file_exists($lockFile)) {
    die('<!DOCTYPE html><html><head><title>Already Installed</title>
    <style>body{font-family:Inter,system-ui,sans-serif;display:flex;justify-content:center;align-items:center;min-height:100vh;background:#f3f6fb;margin:0;}
    .box{background:#fff;padding:40px;border-radius:12px;box-shadow:0 1px 3px rgba(13,27,42,.08),0 8px 24px rgba(13,27,42,.06);text-align:center;max-width:480px;}
    h1{color:#101f33;margin-bottom:12px;} p{color:#718096;} a{color:#12b886;text-decoration:none;font-weight:600;}</style></head>
    <body><div class="box"><h1>Already Installed</h1><p>FreeDNS Panel is already installed. To reinstall, delete the <code>.installed</code> file.</p><p><a href="index.php">&larr; Go to Home</a></p></div></body></html>');
}

if (session_status() === PHP_SESSION_NONE) session_start();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step === 2) {
        $dbHost = trim($_POST['db_host'] ?? 'localhost');
        $dbName = trim($_POST['db_name'] ?? 'freedns');
        $dbUser = trim($_POST['db_user'] ?? 'root');
        $dbPass = $_POST['db_pass'] ?? '';

        try {
            $pdo = new PDO("mysql:host=$dbHost;charset=utf8mb4", $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);

            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $pdo->exec("USE `$dbName`");

            $schema = file_get_contents(__DIR__ . '/schema.sql');
            $schema = preg_replace('/^.*?CREATE DATABASE.*?;/ms', '', $schema);
            $schema = str_replace('USE freedns;', '', $schema);
            $schema = str_replace('freedns', $dbName, $schema);

            $statements = array_filter(array_map('trim', explode(';', $schema)), fn($s) => $s !== '');
            foreach ($statements as $sql) {
                $pdo->exec($sql);
            }

            $_SESSION['install'] = [
                'db_host' => $dbHost,
                'db_name' => $dbName,
                'db_user' => $dbUser,
                'db_pass' => $dbPass,
            ];
            header('Location: install.php?step=3');
            exit;
        } catch (PDOException $e) {
            $errors[] = 'Database error: ' . $e->getMessage();
        }
    }

    if ($step === 3) {
        $inst = $_SESSION['install'] ?? null;
        if (!$inst) {
            header('Location: install.php?step=2');
            exit;
        }

        $adminUser = strtolower(trim($_POST['admin_user'] ?? ''));
        $adminEmail = trim($_POST['admin_email'] ?? '');
        $adminPass = $_POST['admin_pass'] ?? '';
        $adminPass2 = $_POST['admin_pass2'] ?? '';
        $siteName = trim($_POST['site_name'] ?? 'FreeDNS');
        $csrfSecret = bin2hex(random_bytes(32));

        if (strlen($adminUser) < 3) $errors[] = 'Admin username must be at least 3 characters.';
        if (!preg_match('/^[a-z0-9_]+$/', $adminUser)) $errors[] = 'Admin username: lowercase letters, numbers, underscore only.';
        if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'Invalid email address.';
        if (strlen($adminPass) < 8) $errors[] = 'Password must be at least 8 characters.';
        if ($adminPass !== $adminPass2) $errors[] = 'Passwords do not match.';

        if (empty($errors)) {
            try {
                $pdo = new PDO(
                    "mysql:host={$inst['db_host']};dbname={$inst['db_name']};charset=utf8mb4",
                    $inst['db_user'], $inst['db_pass'],
                    [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
                );

                $hash = password_hash($adminPass, PASSWORD_DEFAULT);

                $pdo->exec("DELETE FROM users WHERE username = 'admin'");

                $st = $pdo->prepare('INSERT INTO users (username, email, password_hash, is_admin) VALUES (?, ?, ?, 1)');
                $st->execute([$adminUser, $adminEmail, $hash]);

                $configContent = "<?php\n";
                $configContent .= "/**\n * FreeDNS Panel - configuration\n * Generated by installer on " . date('Y-m-d H:i:s') . "\n */\n\n";
                $configContent .= "// ---- Database ----\n";
                $configContent .= "define('DB_HOST', " . var_export($inst['db_host'], true) . ");\n";
                $configContent .= "define('DB_NAME', " . var_export($inst['db_name'], true) . ");\n";
                $configContent .= "define('DB_USER', " . var_export($inst['db_user'], true) . ");\n";
                $configContent .= "define('DB_PASS', " . var_export($inst['db_pass'], true) . ");\n\n";
                $configContent .= "// ---- App ----\n";
                $configContent .= "define('APP_NAME', 'freedns');\n";
                $configContent .= "define('BASE_URL', '');\n";
                $configContent .= "define('SITE_NAME', " . var_export($siteName, true) . ");\n";
                $configContent .= "define('SESSION_NAME', 'freedns_session');\n\n";
                $configContent .= "// ---- Security / limits ----\n";
                $configContent .= "define('SUB_MAX_LENGTH', 63);\n";
                $configContent .= "define('MIN_PASSWORD', 8);\n";
                $configContent .= "define('CSRF_SECRET', " . var_export($csrfSecret, true) . ");\n";

                file_put_contents(__DIR__ . '/includes/config.php', $configContent);

                $premiumDomains = [
                    ['coolo.com', 0.00, 'Premium short .com domain', 'Premium', 1],
                    ['ezspot.com', 0.00, 'Easy to remember .com', 'Premium', 1],
                    ['flynet.com', 0.00, 'Flying fast .com domain', 'Premium', 1],
                    ['gohere.com', 0.00, 'Direct and simple .com', 'Premium', 1],
                    ['hublab.com', 0.00, 'Lab-grade .com domain', 'Premium', 1],
                    ['instant.org', 0.00, 'Instant free .org subdomain', 'Premium', 1],
                    ['mycloud.org', 0.00, 'Cloud-ready .org domain', 'Premium', 1],
                    ['fastweb.org', 0.00, 'Fast website .org', 'Premium', 1],
                    ['upzone.co', 0.00, 'Short & punchy .co domain', 'Premium', 1],
                    ['onspot.co', 0.00, 'Spot-on .co domain', 'Premium', 1],
                    ['short.io', 0.00, 'Ultra-short .io domain', 'Premium', 1],
                    ['devhq.io', 0.00, 'Developer HQ .io', 'Premium', 1],
                    ['codebase.io', 0.00, 'Code storage .io domain', 'Premium', 1],
                    ['fastmail.co', 0.00, 'Quick mail .co', 'Premium', 0],
                    ['myhost.com', 0.00, 'Personal hosting .com', 'Premium', 0],
                    ['coolvpn.com', 0.00, 'VPN-friendly .com', 'Premium', 0],
                    ['netzone.net', 0.00, 'Network zone .net', 'Premium', 0],
                    ['webstack.co', 0.00, 'Web technology stack .co', 'Premium', 0],
                    ['techbit.io', 0.00, 'Tech bites .io', 'Premium', 0],
                    ['prosite.org', 0.00, 'Professional site .org', 'Premium', 0],
                ];

                $st = $pdo->prepare('INSERT IGNORE INTO domains (name, price, description, category, featured) VALUES (?, ?, ?, ?, ?)');
                foreach ($premiumDomains as $d) {
                    $st->execute($d);
                }

                file_put_contents($lockFile, json_encode([
                    'installed_at' => date('c'),
                    'admin_user' => $adminUser,
                    'db_name' => $inst['db_name'],
                ]));

                unset($_SESSION['install']);
                header('Location: install.php?step=4');
                exit;
            } catch (PDOException $e) {
                $errors[] = 'Database error: ' . $e->getMessage();
            }
        }
    }
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install FreeDNS Panel</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --nc-navy: #101f33; --nc-navy-2: #16273f; --nc-navy-3: #213a5c;
            --nc-teal: #12b886; --nc-teal-d: #0ea472; --nc-orange: #f68b1f;
            --nc-blue: #2f6ff5; --nc-ink: #0d1b2a; --nc-text: #2b3a4d;
            --nc-muted: #718096; --nc-border: #e2e8f0; --nc-bg: #f3f6fb;
            --nc-white: #fff; --nc-red: #e5484d; --nc-green: #12805c;
            --radius: 12px;
            --shadow: 0 1px 3px rgba(13,27,42,.08), 0 8px 24px rgba(13,27,42,.06);
        }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', system-ui, sans-serif; background: var(--nc-bg); color: var(--nc-text); min-height: 100vh; display: flex; flex-direction: column; }
        .install-wrap { flex: 1; display: flex; justify-content: center; align-items: flex-start; padding: 40px 20px; }
        .install-box { background: #fff; border: 1px solid var(--nc-border); border-radius: var(--radius); box-shadow: var(--shadow); width: 100%; max-width: 640px; overflow: hidden; }
        .install-header { background: linear-gradient(135deg, var(--nc-navy) 0%, var(--nc-navy-3) 100%); color: #fff; padding: 30px 36px; }
        .install-header h1 { font-size: 1.6rem; font-weight: 800; display: flex; gap: 4px; margin-bottom: 6px; }
        .install-header .brand-mark { background: var(--nc-teal); padding: 2px 10px; border-radius: 6px 0 0 6px; }
        .install-header .brand-accent { background: var(--nc-orange); padding: 2px 10px; border-radius: 0 6px 6px 0; }
        .install-header p { color: #b9c9e0; font-size: .92rem; }
        .install-body { padding: 36px; }
        .steps { display: flex; gap: 0; margin-bottom: 32px; }
        .step-item { flex: 1; text-align: center; padding: 12px 8px; position: relative; font-size: .82rem; font-weight: 600; color: var(--nc-muted); }
        .step-item::after { content: ''; position: absolute; top: 50%; right: -50%; width: 100%; height: 2px; background: var(--nc-border); z-index: 0; }
        .step-item:last-child::after { display: none; }
        .step-item .step-num { display: inline-flex; width: 30px; height: 30px; border-radius: 50%; background: var(--nc-border); color: var(--nc-muted); align-items: center; justify-content: center; font-size: .85rem; margin-bottom: 6px; position: relative; z-index: 1; }
        .step-item.active .step-num { background: var(--nc-teal); color: #fff; }
        .step-item.active { color: var(--nc-teal); }
        .step-item.done .step-num { background: var(--nc-green); color: #fff; }
        .step-item.done { color: var(--nc-green); }
        .step-item.done::after { background: var(--nc-green); }
        h2 { font-size: 1.25rem; color: var(--nc-ink); margin-bottom: 6px; }
        .sub { color: var(--nc-muted); font-size: .9rem; margin-bottom: 24px; }
        .form-group { margin-bottom: 18px; }
        .form-group label { display: block; font-weight: 600; font-size: .88rem; margin-bottom: 6px; color: var(--nc-ink); }
        .form-group .hint { font-size: .8rem; color: var(--nc-muted); margin-top: 4px; }
        input[type="text"], input[type="email"], input[type="password"], input[type="number"] {
            width: 100%; padding: 11px 14px; border: 1px solid var(--nc-border); border-radius: 10px;
            font-size: .95rem; font-family: inherit; color: var(--nc-ink); background: #fff;
            transition: border-color .15s, box-shadow .15s; outline: none;
        }
        input:focus { border-color: var(--nc-blue); box-shadow: 0 0 0 3px rgba(47,111,245,.15); }
        .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
        .btn { display: inline-flex; align-items: center; justify-content: center; gap: 8px; padding: 12px 28px; border-radius: 999px; border: 1px solid transparent; font-weight: 600; font-size: .95rem; cursor: pointer; transition: all .15s; text-decoration: none; }
        .btn-primary { background: var(--nc-teal); color: #fff; }
        .btn-primary:hover { background: var(--nc-teal-d); transform: translateY(-1px); box-shadow: 0 6px 16px rgba(18,184,134,.35); }
        .btn-lg { padding: 14px 34px; font-size: 1rem; }
        .btn-block { width: 100%; }
        .alert { padding: 12px 18px; border-radius: var(--radius); margin-bottom: 18px; font-size: .9rem; font-weight: 500; }
        .alert-error { background: #fdecec; color: var(--nc-red); border: 1px solid #f6c6c6; }
        .alert-success { background: #e6f7f0; color: var(--nc-green); border: 1px solid #b7e6d2; }
        .alert-info { background: #e8f0fe; color: #1c4fd6; border: 1px solid #c3d6fb; }
        .checklist { list-style: none; padding: 0; margin: 20px 0; }
        .checklist li { padding: 10px 16px; border: 1px solid var(--nc-border); border-radius: 10px; margin-bottom: 8px; display: flex; align-items: center; gap: 10px; font-size: .92rem; }
        .checklist li .icon-ok { color: var(--nc-green); font-weight: 700; }
        .checklist li .icon-fail { color: var(--nc-red); font-weight: 700; }
        .success-box { text-align: center; padding: 40px 20px; }
        .success-box .big-icon { font-size: 4rem; margin-bottom: 16px; }
        .success-box h2 { margin-bottom: 12px; }
        .success-box .cred-table { margin: 20px auto; text-align: left; border-collapse: collapse; }
        .success-box .cred-table td { padding: 8px 16px; border-bottom: 1px solid var(--nc-border); }
        .success-box .cred-table td:first-child { font-weight: 600; color: var(--nc-muted); }
        code { background: var(--nc-bg); padding: 2px 8px; border-radius: 6px; font-size: .88rem; }
        .footer-note { text-align: center; padding: 20px; color: var(--nc-muted); font-size: .82rem; }
        @media (max-width: 600px) { .form-row { grid-template-columns: 1fr; } .install-body { padding: 24px; } }
    </style>
</head>
<body>
    <div class="install-wrap">
        <div class="install-box">
            <div class="install-header">
                <h1><span class="brand-mark">free</span><span class="brand-accent">dns</span></h1>
                <p>Installation Wizard</p>
            </div>
            <div class="install-body">
                <div class="steps">
                    <div class="step-item <?php echo $step >= 1 ? ($step > 1 ? 'done' : 'active') : ''; ?>">
                        <div class="step-num">1</div>
                        <div>Requirements</div>
                    </div>
                    <div class="step-item <?php echo $step >= 2 ? ($step > 2 ? 'done' : 'active') : ''; ?>">
                        <div class="step-num">2</div>
                        <div>Database</div>
                    </div>
                    <div class="step-item <?php echo $step >= 3 ? ($step > 3 ? 'done' : 'active') : ''; ?>">
                        <div class="step-num">3</div>
                        <div>Admin Account</div>
                    </div>
                    <div class="step-item <?php echo $step >= 4 ? 'done active' : ''; ?>">
                        <div class="step-num">4</div>
                        <div>Complete</div>
                    </div>
                </div>

                <?php foreach ($errors as $err): ?>
                    <div class="alert alert-error"><?php echo htmlspecialchars($err); ?></div>
                <?php endforeach; ?>

                <?php if ($step === 1): ?>
                    <h2>Welcome to FreeDNS Panel</h2>
                    <p class="sub">Before we begin, let's make sure your server meets the requirements.</p>
                    <?php
                    $checks = [
                        ['PHP 8.0+', version_compare(PHP_VERSION, '8.0.0', '>=')],
                        ['PDO MySQL extension', extension_loaded('pdo_mysql')],
                        ['Session support', function_exists('session_start')],
                        ['config.php writable', is_writable(__DIR__ . '/includes/')],
                        ['MySQL/MariaDB', true],
                    ];
                    ?>
                    <ul class="checklist">
                        <?php foreach ($checks as $ck): ?>
                            <li>
                                <span class="<?php echo $ck[1] ? 'icon-ok' : 'icon-fail'; ?>"><?php echo $ck[1] ? '&#10003;' : '&#10007;'; ?></span>
                                <?php echo $ck[0]; ?>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <?php if ($checks[1][1] && $checks[3][1]): ?>
                        <a href="install.php?step=2" class="btn btn-primary btn-lg btn-block">Continue &rarr;</a>
                    <?php else: ?>
                        <div class="alert alert-error">Please fix the issues above before continuing.</div>
                    <?php endif; ?>

                <?php elseif ($step === 2): ?>
                    <h2>Database Configuration</h2>
                    <p class="sub">Enter your MySQL/MariaDB credentials. The database will be created if it doesn't exist.</p>
                    <form method="post" action="install.php?step=2">
                        <div class="form-row">
                            <div class="form-group">
                                <label>DB Host</label>
                                <input type="text" name="db_host" value="localhost" required>
                            </div>
                            <div class="form-group">
                                <label>DB Name</label>
                                <input type="text" name="db_name" value="freedns" required>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label>DB Username</label>
                                <input type="text" name="db_user" value="root" required>
                            </div>
                            <div class="form-group">
                                <label>DB Password</label>
                                <input type="password" name="db_pass" value="">
                                <div class="hint">Leave empty if no password.</div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Test Connection &amp; Create Database &rarr;</button>
                    </form>

                <?php elseif ($step === 3): ?>
                    <h2>Create Admin Account</h2>
                    <p class="sub">Set up your administrator login. This account will have full control over the panel.</p>
                    <form method="post" action="install.php?step=3">
                        <div class="form-group">
                            <label>Admin Username</label>
                            <input type="text" name="admin_user" placeholder="admin" required minlength="3" pattern="[a-z0-9_]+" title="Lowercase letters, numbers, underscore only">
                            <div class="hint">This will be your login username. Must be unique.</div>
                        </div>
                        <div class="form-group">
                            <label>Admin Email</label>
                            <input type="email" name="admin_email" placeholder="admin@yourdomain.com" required>
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" name="admin_pass" required minlength="8">
                            </div>
                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input type="password" name="admin_pass2" required minlength="8">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Site Name</label>
                            <input type="text" name="site_name" value="FreeDNS">
                            <div class="hint">Display name shown in the header and browser tab.</div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Create Account &amp; Finish &rarr;</button>
                    </form>

                <?php elseif ($step === 4): ?>
                    <div class="success-box">
                        <div class="big-icon">&#10003;</div>
                        <h2>Installation Complete!</h2>
                        <p class="sub">FreeDNS Panel is ready. Your admin account has been created with premium domains pre-loaded.</p>
                        <table class="cred-table">
                            <tr><td>Admin URL</td><td><code><?php echo htmlspecialchars((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['REQUEST_URI'])); ?>/admin/index.php</code></td></tr>
                            <tr><td>Admin User</td><td><code><?php echo htmlspecialchars($adminUser ?? 'admin'); ?></code></td></tr>
                            <tr><td>Domains loaded</td><td><code>20 premium + 10 starter</code></td></tr>
                        </table>
                        <br>
                        <a href="login.php" class="btn btn-primary btn-lg" style="margin-right:8px;">Login &rarr;</a>
                        <a href="admin/index.php" class="btn btn-primary btn-lg" style="background:var(--nc-orange);">Admin Panel &rarr;</a>
                        <br><br>
                        <div class="alert alert-info" style="text-align:left;">For security, delete or rename <code>install.php</code> after first login. The <code>.installed</code> lock file prevents re-installation.</div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="footer-note">&copy; <?php echo date('Y'); ?> FreeDNS Panel. Installation Wizard.</div>
        </div>
    </div>
</body>
</html>
